### ISSUE TITLE
sslmode=require in docker image

### ISSUE THREAD

**Issue by scottrobertson** [getsentry/onpremise#201]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Cannot connect to PGDB when starting the docker image due to it requiring sslmode=require. I see no way to set this as a env var etc.

## Steps to Reproduce

1. Set the DB env vars 
2. Try and start the docker image
3. It will fail to connect to the DB due to requiring SSL.

Good items to include here include:

```
OperationalError: could not create SSL context: library has no ciphers
FATAL:  no pg_hba.conf entry for host "*****", user "doadmin", database "sentry", SSL off

08:13:02 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
```

### What you expected to happen

Should be able to set an SSLMODE env var

### Possible Solution

Allow the config to be set by env var. Example of config: https://github.com/BCCVL/sentry/blob/master/sentry.conf.py#L60

**Comment by BYK** [comment]
@insertjokehere  - thanks a lot for sharing your solution. So the permanent solution for us is to upgrade psycopg2? I'd love to get this fixed in the repo for 9.1.2 if there is a good fix we can incorporate into sentry or onpremise repos.

**Comment by mattrobenolt** [comment]
I don't think we need to upgrade psycopg2, at least we shouldn't. But it seems that maybe we don't have the correct headers around when installing it to get the right SSL contexts? I'm not sure, but I'd say if the answer is to upgrade psycopg2, we're probably gonna have a bad time.

It seems the answers in here support not needing to do that. It's probably more that we need libssl or whatever the development headers are when installing, if we're not doing that already.

Alternatively, I'd like to investigate if we switch to [psycopg2-binary](https://pypi.org/project/psycopg2-binary/) if that solves the issue too. This package is just a re-packaging of psycopg2 that is more recommended since it's a compiled whl and should contain what's needed already. I'd like to switch to using this regardless at some point in the future since it's just a drop in replacement.

**Comment by BYK** [comment]
Can you all please try this again with 9.1.2 (which is what the latest master points to now). If this is fixed, I'll close the issue, if not we'll investigate more.

**Comment by davidchua** [comment]
I have a similar issue with OP. I have a postgres database that requires `sslmode`.

Using the official sentry docker image of `9.1.2`, I get a

```
django.db.utils.OperationalError: could not create SSL context: library has no ciphers
FATAL:  SSL connection is required. Please specify SSL options and retry.
```

**Comment by BYK** [comment]
@davidchua - yours look like a different issue to me, related to the move from `psycopg2` to ` psycopg2-binary` in the 9.1.2 release. I'd recommend using 9.1.1 for now or try modifying the base Docker image here to install the latest version of `psycopg2-binary` (2.8.3) to see if it fixes the problem (it may as it is using a newer version of OpenSSL). I'll also try if we can get this to getsentry/sentry but I wouldn't be keen on releasing a 9.1.3 unless this affects a wide range of people.

**Comment by davidchua** [comment]
@BYK Sorry, my github notification is a bit wonky, didn't see your reply till now.

`sentry:9.1.1` also has the same issue for me

**Comment by scottrobertson** [comment]
Just tried `9.1.2`. Still fails when trying to connect to DB that requires SSL.

**Comment by anitabee** [comment]
Had the same issue and pinning the version to `psycopg2-binary>=2.8.3,<2.9.0` in my req.txt file solves the issue for me.
I use https://github.com/getsentry/docker-sentry/blob/master/9.1/onbuild/Dockerfile as my base image and run `RUN pip install -r /tmp/req.txt` from it.

**Comment by CH-anhngo** [comment]
we hitting the same issue. Running `9.1.2` also. What can we do to resolve it ?

**Comment by BYK** [comment]
@CH-anhngo have you tried this: https://github.com/getsentry/onpremise/issues/201#issuecomment-542891780

**Comment by CH-anhngo** [comment]
@BYK I didn't try it yet. We just using what out of helm/sentry. So I guest we need to build a customize image for sentry and run it in our k8s ?

**Comment by CH-anhngo** [comment]
still hitting this after rebuild follow the @anitabee comment above :(
```
sentry-web-bb56c776c-hnrcl sentry-web OperationalError: could not create SSL context: library has no ciphers
sentry-web-bb56c776c-hnrcl sentry-web FATAL:  no pg_hba.conf entry for host "10.16.73.89", user "sentry", database "sentry", SSL off
sentry-web-bb56c776c-hnrcl sentry-web 00:58:30 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
```

**Comment by anitabee** [comment]
This seams more like your DB has `sslmode=on` but that is not happening from Django's side? If so in [OPTIONS](https://github.com/getsentry/docker-sentry/blob/0faaf4d440e5ae9cfb5b37ffd7e051272594c0be/9.1/sentry.conf.py#L72) you would need to add something like:                 
`'sslmode': 'require',`

**Comment by anitabee** [comment]
Also other solution that worked: https://github.com/getsentry/onpremise/issues/201#issuecomment-493843675

**Comment by anhvngo** [comment]
> Also could be that your DB has `sslmode=on` but that is not happening from Django's side? If so in sentry.conf.py [OPTIONS](https://github.com/getsentry/docker-sentry/blob/0faaf4d440e5ae9cfb5b37ffd7e051272594c0be/9.1/sentry.conf.py#L72) you would need to add something like:
> `'sslmode': 'require',`

I tried the custom build with/without `'sslmode':'require'` but neither works.

**Comment by anhvngo** [comment]
> Also other solution that worked: [#201 (comment)](https://github.com/getsentry/onpremise/issues/201#issuecomment-493843675)

Tried this suggestion but my `docker build ` keep failing. Can you share the Dockerfile ?

**Comment by CH-anhngo** [comment]
> @CH-anhngo have you tried this: [#201 (comment)](https://github.com/getsentry/onpremise/issues/201#issuecomment-542891780)

this does not work either:
```
Step 9/9 : RUN pip install --no-binary :all:
 ---> Running in b329a100d224
ERROR: You must give at least one requirement to install (see "pip help install")
The command '/bin/sh -c pip install --no-binary :all:' returned a non-zero code: 1
```

> Also could be that your DB has `sslmode=on` but that is not happening from Django's side? If so in sentry.conf.py [OPTIONS](https://github.com/getsentry/docker-sentry/blob/0faaf4d440e5ae9cfb5b37ffd7e051272594c0be/9.1/sentry.conf.py#L72) you would need to add something like:
> `'sslmode': 'require',`

I used the require mode also with custom build image but still hitting error :(

**Comment by CH-anhngo** [comment]
> Also other solution that worked: [#201 (comment)](https://github.com/getsentry/onpremise/issues/201#issuecomment-493843675)

The build keep failing on me. Can you share the Dockerfile ?
```
Step 9/9 : RUN PSYCOPG=$(pip freeze | grep psycopg2) 	&& pip uninstall -y $PSYCOPG 	&& pip install --no-binary :all: $PSYCOPG
 ---> Running in 53e54f9d91f6
Collecting psycopg2-binary==2.8.4
  Downloading https://files.pythonhosted.org/packages/00/7b/a623f49b3248957e7eaaac52eba1117209775d54e7a8501c460473a7ba4f/psycopg2-binary-2.8.4.tar.gz (378kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Ca_ZNf/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Ca_ZNf/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-Ca_ZNf/psycopg2-binary/pip-egg-info
         cwd: /tmp/pip-install-Ca_ZNf/psycopg2-binary/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-Ca_ZNf/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info
    writing /tmp/pip-install-Ca_ZNf/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing top-level names to /tmp/pip-install-Ca_ZNf/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing dependency_links to /tmp/pip-install-Ca_ZNf/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing manifest file '/tmp/pip-install-Ca_ZNf/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
```

**Comment by anitabee** [comment]
Yes sure, I had two versions that worked for me when I run it from custom image:

Dockerfile:

```
FROM sentry:9.1-onbuild
RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q libxslt1-dev libldap2-dev libsasl2-dev libssl-dev   

COPY req.txt /tmp/
RUN pip install -r /tmp/req.txt

RUN apt-get remove -y -q libxslt1-dev libldap2-dev libsasl2-dev libssl-dev 
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/*
RUN usermod -u 1001 sentry
```

req.txt version 1:
```
# TODO
# ERROR: sentry 9.1.2 has requirement Django<1.7,>=1.6.11, but you'll have django 1.11.26 which is incompatible.
Django<1.7,>=1.6.11
psycopg2==2.7.3 --no-binary=psycopg2 
```

req.txt version 2:
```
psycopg2-binary>=2.7.0,<2.9.0
```
Also I switched from [getsentry/onbuild](https://github.com/getsentry/docker-sentry/blob/master/9.1/onbuild/Dockerfile) to [getsentry](https://github.com/getsentry/docker-sentry/blob/master/9.1/Dockerfile) version, I'm not using this custom image any-more I moved most of this config/installation to chart, so didn't have much use from onbuild...

**Comment by CH-anhngo** [comment]
> Yes sure, I had two versions that worked for me when I run it from custom image:
> 
> Dockerfile:
> 
> ```
> FROM sentry:9.1-onbuild
> RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q libxslt1-dev libldap2-dev libsasl2-dev libssl-dev   
> 
> COPY req.txt /tmp/
> RUN pip install -r /tmp/req.txt
> 
> RUN apt-get remove -y -q libxslt1-dev libldap2-dev libsasl2-dev libssl-dev 
> RUN rm -rf /var/lib/apt/lists/*
> RUN rm -rf /tmp/*
> RUN usermod -u 1001 sentry
> ```
> 
> req.txt version 1:
> 
> ```
> # TODO
> # ERROR: sentry 9.1.2 has requirement Django<1.7,>=1.6.11, but you'll have django 1.11.26 which is incompatible.
> Django<1.7,>=1.6.11
> psycopg2==2.7.3 --no-binary=psycopg2 
> ```
> 
> req.txt version 2:
> 
> ```
> psycopg2-binary>=2.7.0,<2.9.0
> ```
> 
> Also I switched from [getsentry/onbuild](https://github.com/getsentry/docker-sentry/blob/master/9.1/onbuild/Dockerfile) to [getsentry](https://github.com/getsentry/docker-sentry/blob/master/9.1/Dockerfile) version, I'm not using this custom image any-more I moved most of this config/installation to chart, so didn't have much use from onbuild...

so you mean `getsentry` 9.1 works for you with SSL require ?

**Comment by anitabee** [comment]
@CH-anhngo yes I'm running  getsentry 9.1 with SSL require, still no luck?

**Comment by CH-anhngo** [comment]
> @CH-anhngo yes I'm running getsentry 9.1 with SSL require, still no luck?
@anitabee 
It works for us only with `9.0` as soon as we switch to `9.1` it throws out the same error. Wondering what `9.1` docker image did you use ? or you build the custom image for 9.1 ? 
thanks,

**Comment by BYK** [comment]
We're not planning to work on this for now so closing as wontfix.

**Comment by Bessonov** [comment]
@BYK but if you write `for now`, then why did you close the issue? From my point of view, the issue isn't resolved and should stay open. BTW, we run in the same issue and because the database allows ssl connections only, we have a hard time to use sentry.

**Comment by BYK** [comment]
@Bessonov we are dedicating our resources to support the recommended setup here in this repo, based on docker-compose and the issue does not apply to that so we are not going to work on this at all probably.

This repo has a certain direction which does not align with this issue, so closing it as wontfix is a stronger signal to anyone interested, rather than keeping it open forever.
