### ISSUE TITLE
Announce Python 3 support

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/onpremise#797]
Ticketing from an email thread with @BYK @eurica @bruno-garcia. Now that we're on Python 3, we should coordinate a significant upgrade campaign, based on [Python 2's EOL](https://www.python.org/doc/sunset-python-2/) and the security risks associated with that. We would invoke the Sentry 9 beacon for this, even though it has a bug causing the nagging broadcast to show up too frequently. We would also use email like we did for the BSL announcement.

Sample messaging esp wrt Sentry 9 self-hosters:

> 1. You are running Python 2 which has been EoL-ed, and even if you're ok with that, I bet someone in your compliance department isn't 
> 1. Here's how to upgrade...
> 1. But since you last installed Sentry > 2 years ago we've become a much more respectable company from a compliance perspective: SOC2, more money raised, more customers, we even have Single Tenant
> 1. Why not revisit the OSS/SaaS discussion, instead of doing the upgrade yourself?  Would you like to talk to a human being in SE or Support?

### Todo

- [ ] Make sure "how to upgrade" docs are tight.
- [ ] Write upgrade message (different for different audiences?).
- [ ] Compile email list.
- [ ] Send email.
- [ ] Push via beacon.

**Comment by chadwhitacre** [comment]
This is way more than docs.

**Comment by eurica** [comment]
At the end of the day, if companies are comfortable sticking with Py2 then that's up to them. But let's do what we can to make sure they make an informed decision.  Docs is part of it, but I can't imagine too many people regularly check the docs to see if their old software has fallen out of support :)

**Comment by chadwhitacre** [comment]
I've updated the description with an initial TODO.

**Comment by BYK** [comment]
@chadwhitacre does this even make sense at this point?

**Comment by chadwhitacre** [comment]
We could probably still do this from a "Python 3 is relevant" point of view. But I think this would need to get quarterly goal visibility for it to be done right, and I don't see us prioritizing this this year since we're focused on customer engagement instead. Closing.
